/*
    This file is part of JQNetwork
    
    Library introduce: https://github.com/188080501/JQNetwork

    Copyright: Jason

    Contact email: Jason@JasonServer.com
    
    GitHub: https://github.com/188080501/
*/

#ifndef JQNETWORK_INCLUDE_JQNETWORK_FORWARF_INC
#define JQNETWORK_INCLUDE_JQNETWORK_FORWARF_INC

// JQNetwork lib import
#include "jqnetwork_forwarf.h"

#endif//JQNETWORK_INCLUDE_JQNETWORK_FORWARF_INC
