include($$PWD/WelcomeGroup/WelcomeGroup.pri)
include($$PWD/TextGroup/TextGroup.pri)
include($$PWD/CalculateGroup/CalculateGroup.pri)
include($$PWD/MakeGroup/MakeGroup.pri)
include($$PWD/ToolsGroup/ToolsGroup.pri)
include($$PWD/QtGroup/QtGroup.pri)
