include($$PWD/Welcome/Welcome.pri)
include($$PWD/PngWarningRemover/PngWarningRemover.pri)
include($$PWD/Utf16Transform/Utf16Transform.pri)
include($$PWD/HashCalculate/HashCalculate.pri)
include($$PWD/IconMaker/IconMaker.pri)
